name: Build and Publish Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version

      - name: Build Micronaut project
        run: |
          cd micronaut
          ./gradlew dockerBuildNative
          docker tag app:latest mraible/micronaut:latest
        shell: bash

      - name: Build Quarkus project
        run: |
          cd quarkus
          ./gradlew build -Dquarkus.package.type=native
          docker build -f src/main/docker/Dockerfile.native -t quarkus .
          docker tag quarkus mraible/quarkus
        shell: bash

      - name: Build Spring Boot project
        run: |
          cd spring-boot
          ./gradlew bootBuildImage --imageName=spring-boot
          docker tag spring-boot mraible/spring-boot
        shell: bash

      - name: Build Helidon project
        run: |
          cd helidon
          docker build -t helidon -f Dockerfile.native .
          docker tag helidon mraible/helidon
        shell: bash

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Publish Micronaut Docker image to DockerHub
        run: |
          docker push mraible/micronaut
        shell: bash

      - name: Publish Quarkus Docker image to DockerHub
        run: |
          docker push mraible/quarkus
        shell: bash

      - name: Publish Spring Boot Docker image to DockerHub
        run: |
          docker push mraible/spring-boot
        shell: bash

      - name: Publish Helidon Docker image to DockerHub
        run: |
          docker push mraible/helidon
        shell: bash
